# Generated by Django 5.1.4 on 2024-12-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='уровень иерархии'),
        ),
    ]
